server:
  port: 8080
  error:
    include-stacktrace: on_param

spring:
  profiles:
    active: chaos-monkey
  datasource:
    url: jdbc:mysql://localhost:3306/book?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: books
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: "us-east-1"
    s3:
        url: https://s3.us-east-1.amazonaws.com/
        bucket: ${BUCKET_NAME}
external:
  url: "http://localhost:8081"

chaos:
  monkey:
    enabled: true
    watcher:
      service: true
      restController: true
    assaults:
      level: 1
      latencyActive: true
      latencyRangeStart: 2000
      latencyRangeEnd: 5000

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"