DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS USERS(
 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
 AUTHHORITIES VARCHAR(255) NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 USERNAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    BOOK_CATEGORY VARCHAR(255) NULL
);