name: Check PR (book)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-checking:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: check main
      run: ./gradlew checkStyleMain

    - name: check test
      run: ./gradlew checkStyleTest

    - name: check integration test
      run: ./gradlew checkStyleIntegrationTest

  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit Tests
        run: ./gradlew test -x integrationTest

      - name: Integration Tests
        run: ./gradlew integrationTest
